### ISSUE TITLE
i can't install! help ...

### ISSUE THREAD

**Issue by helloitu** [shevabam/mysql-backup#1]
root@gauDell0R14N:~/mysql-backup-master# composer require --dev "phelium/mysql-backup": "dev-master"
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted

  [InvalidArgumentException]  
  Could not find package dev-master at any version for your minimum-stability  
   (dev). Check the package spelling or your minimum-stability                 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

---

 help ....

**Comment by shevabam** [comment]
Hello,

The right syntax is : 

`composer require --dev phelium/mysql-backup:dev-master`

**Comment by helloitu** [comment]
thanks :+1:
